language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_script:
  - "cd tests"
  - "python bootstrap.py"
  - "python bin/buildout"
# command to run tests
script: bin/nosetests
